import { Router } from "express";
import * as controller from "./resources.controller.js";
import { authenticate } from "../../middleware/auth.middleware.js";
import { requireContentAdmin } from "../../middleware/role.middleware.js";
const router = Router();
router.get("/", controller.getAll);
router.post("/", authenticate, requireContentAdmin, controller.create);
router.put("/:id", authenticate, requireContentAdmin, controller.update);
router.delete("/:id", authenticate, requireContentAdmin, controller.remove);
export default router;